// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60fQeVX8PLrALRxoWk_j5DKSs_XVSews',
    appId: '1:438878395174:web:your-web-app-id',
    messagingSenderId: '438878395174',
    projectId: 'mindle-953ac',
    authDomain: 'mindle-953ac.firebaseapp.com',
    storageBucket: 'mindle-953ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA60fQeVX8PLrALRxoWk_j5DKSs_XVSews',
    appId: '1:438878395174:android:1mjsgiko7mu4e2o657ottj8vcdvnbb1s',
    messagingSenderId: '438878395174',
    projectId: 'mindle-953ac',
    storageBucket: 'mindle-953ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA60fQeVX8PLrALRxoWk_j5DKSs_XVSews',
    appId: '1:438878395174:ios:321c2c5a16d0f53f683fe7',
    messagingSenderId: '438878395174',
    projectId: 'mindle-953ac',
    storageBucket: 'mindle-953ac.firebasestorage.app',
    iosBundleId: 'com.ethanpark.mindle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA60fQeVX8PLrALRxoWk_j5DKSs_XVSews',
    appId: '1:438878395174:ios:321c2c5a16d0f53f683fe7',
    messagingSenderId: '438878395174',
    projectId: 'mindle-953ac',
    storageBucket: 'mindle-953ac.firebasestorage.app',
    iosBundleId: 'com.ethanpark.mindle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA60fQeVX8PLrALRxoWk_j5DKSs_XVSews',
    appId: '1:438878395174:web:your-web-app-id',
    messagingSenderId: '438878395174',
    projectId: 'mindle-953ac',
    authDomain: 'mindle-953ac.firebaseapp.com',
    storageBucket: 'mindle-953ac.firebasestorage.app',
  );
}
